---
externaldns_vars:
  cloudflare:
    acme:
      # -- Available options are `production` and `staging`
      server: staging
    api:
      token:
        key: token
        name: cloudflare-api-token
    host:
      domain: noty.cc
    tls:
      cluster_issuer:
        name: cloudflare-cluster-issuer
      key_prefix: cloudflare
  kubernetes:
    helm:
      chart:
        name: external-dns
        version: v1.15.0
      repository:
        name: external-dns
        org: kubernetes-sigs
        url: https://kubernetes-sigs.github.io
    log_level: warning
    namespace: kube-system
    policy: sync
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
