---
- name: Role Post-Install
  when: ansible_host in k3s_map.server.hosts
  run_once: true
  block:
    - name: Metrics Setup
      when: argocd_map.metrics.service.monitor.enabled
      block:
        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            argocd_postinstall: true

        - name: Update chart postinstall values
          kubernetes.core.helm:
            chart_ref: '{{ argocd_map.helm.chart.reference }}'
            chart_version: '{{ argocd_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ argocd_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ argocd_vars.kubernetes.namespace }}'
            timeout: '{{ argocd_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            reset_values: false
            reuse_values: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

    - name: Update server user credentials
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
        kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
        wait: true
      no_log: true

    - name: Gateway Setup
      when: externaldns_vars.cloudflare.host.domain | lower != 'disabled'
      block:
        - name: Create server gateway
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'gateway.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true

        - name: Create insecure http route
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true

        - name: Create secure http route
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
