---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert-manager
    - external-dns
    - k3s
    - victoria-metrics
    - argo-cd
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ argocd_project.url }}/{{ argocd_project.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release checksum url
      ansible.builtin.uri:
        url: '{{ argocd_project.release.checksum }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release file url
      ansible.builtin.uri:
        url: '{{ argocd_project.release.file }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Validate configuration params values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_params.j2') | trim }}"

        - name: Validate configuration rbac values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_rbac.j2') | trim }}"

        - name: Validate credentials values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'credentials.j2') }}"

        - name: Validate gateway values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'gateway.j2') }}"

        - name: Validate insecure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') }}"

        - name: Validate secure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') }}"

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            argocd_postinstall: false

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            argocd_postinstall: true

        - name: Validate postinstall chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Add repository
          kubernetes.core.helm_repository:
            name: '{{ argocd_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ argocd_map.helm.repository.url }}'

        - name: Simulate chart deployment
          ansible.builtin.command:
            cmd: >-
              helm diff upgrade {{ argocd_vars.kubernetes.helm.chart.name }} {{ argocd_map.helm.chart.reference }}
                --kubeconfig {{ k3s_project.cluster.kubeconfig }}
                --namespace {{ argocd_vars.kubernetes.namespace }}
                --version {{ argocd_vars.kubernetes.helm.chart.version }}
                --context 3 --values -
            stdin: "{{ lookup('ansible.builtin.template', 'values.j2') }}"
          register: result
          delay: 1
          retries: 3
          until: result is not failed
          changed_when: false

        - name: Chart deployment simulation result
          ansible.builtin.debug:
            msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"
