---
- name: Set map fact
  ansible.builtin.set_fact:
    helm_map:
      environment:
        HELM_CACHE_HOME: '{{ helm_vars.directory.share }}/cache'
        HELM_CONFIG_HOME: '{{ helm_vars.directory.share }}/config'
        HELM_DATA_HOME: '{{ helm_vars.directory.share }}'
        HELM_PLUGINS: '{{ helm_vars.directory.share }}/plugins'
        HELM_REGISTRY_CONFIG: '{{ helm_vars.directory.share }}/config/registry/config.json'
        HELM_REPOSITORY_CACHE: '{{ helm_vars.directory.share }}/cache/repository'
        HELM_REPOSITORY_CONFIG: '{{ helm_vars.directory.share }}/config/repositories.yaml'
      release:
        channel: '{{ helm_vars.release.repository.url }}/{{ helm_vars.release.repository.channel }}'
        key: '{{ helm_vars.release.repository.url }}/{{ helm_vars.release.repository.key }}'
  run_once: true

- name: Set plugin packages fact
  ansible.builtin.set_fact:
    helm_plugin_packages: '{{ plugin.packages }}'
  loop: '{{ helm_vars.plugins }}'
  loop_control:
    loop_var: plugin
  run_once: true
  when:
    - plugin.enabled
    - plugin.packages is defined

- name: Set plugin packages disabled fact
  ansible.builtin.set_fact:
    helm_plugin_packages_disabled: '{{ plugin.packages }}'
  loop: '{{ helm_vars.plugins }}'
  loop_control:
    loop_var: plugin
  run_once: true
  when:
    - not plugin.enabled
    - plugin.packages is defined
