---
repos:
  - repo: https://github.com/axivo/k3s-cluster
    rev: v1.0.0
    hooks:
      - id: argo-cd
        args:
          - --chart-search-root=./roles/argocd
      - id: cert-manager
        args:
          - --chart-search-root=./roles/certmanager
      - id: victoria-metrics-k8s-stack
        args:
          - --chart-search-root=./roles/victoriametrics
