---
- name: Cluster Upgrade
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Role Upgrade
      ansible.builtin.include_role:
        apply:
          tags: '{{ upgrade }}'
        name: '{{ upgrade }}'
        tasks_from: upgrade
      loop:
        - argocd
        - certmanager
        - cilium
        - cloudflare
        - cluster
        - helm
        - k3s
        - kured
        - longhorn
        - victorialogs
        - victoriametrics
      loop_control:
        loop_var: upgrade
      tags: always
      when: upgrade in ansible_run_tags
