---
- name: Cluster Validation
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Validate global settings
      ansible.builtin.include_role:
        name: '{{ validation }}'
        tasks_from: validation
      loop:
        - cluster
        - k3s
        - argocd
        - certmanager
        - cilium
        - externaldns
        - helm
        - kured
        - longhorn
        - victorialogs
        - victoriametrics
      loop_control:
        loop_var: validation
