---
- name: Role Post-Install
  when: ansible_host in k3s_map.server.hosts
  run_once: true
  block:
    - name: Gateway Setup
      when: externaldns_vars.cloudflare.host.domain | lower != 'disabled'
      block:
        - name: Create hubble ui gateway
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'gateway.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
            wait: true

        - name: Create hubble ui http insecure route
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
            wait: true

        - name: Create hubble ui http secure route
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
            wait: true

    - name: Hubble TLS
      when: cilium_vars.kubernetes.hubble.tls.auto.method | lower == 'certmanager'
      block:
        - name: Create hubble certificate
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'certificate.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
            wait: true

        - name: Create hubble cluster issuer
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
            wait: true

    - name: Set chart setup fact
      ansible.builtin.set_fact:
        cilium_setup: false

    - name: Set chart postinstall fact
      ansible.builtin.set_fact:
        cilium_postinstall: true

    - name: Update chart postinstall values
      kubernetes.core.helm:
        chart_ref: '{{ cilium_map.helm.chart.reference }}'
        chart_version: '{{ cilium_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
        name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ cilium_vars.kubernetes.namespace }}'
        timeout: '{{ cilium_map.helm.timeout }}'
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        reset_values: false
        reuse_values: true
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
