---
- name: Set map fact
  ansible.builtin.set_fact:
    longhorn_map:
      helm:
        chart:
          reference: '{{ longhorn_vars.kubernetes.helm.repository.org }}/{{ longhorn_vars.kubernetes.helm.chart.name }}'
        repository:
          name: '{{ longhorn_vars.kubernetes.helm.repository.org }}/{{ longhorn_vars.kubernetes.helm.repository.name }}'
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    longhorn_project:
      tag: '{{ longhorn_vars.kubernetes.helm.chart.version }}'
      url: https://github.com/{{ longhorn_map.helm.repository.name }}/releases/tag
  run_once: true
