---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - cloudflare
    - k3s

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        state: drained
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ longhorn_vars.kubernetes.helm.repository.org }}'
        repo_url: '{{ longhorn_vars.kubernetes.helm.repository.url }}'

    - name: Chart Setup
      run_once: true
      block:
        - name: Create backup secret
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'secret.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
            wait: true
          when:
            - longhorn_vars.kubernetes.default_settings.backup.enabled
            - longhorn_vars.kubernetes.default_settings.backup.target[:4] | lower == 'cifs'
          no_log: true

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            longhorn_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ longhorn_project_chart }}'
            chart_version: '{{ longhorn_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
            name: '{{ longhorn_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ longhorn_vars.kubernetes.namespace }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Gateway Setup
          when: cloudflare_vars.kubernetes.host.domain | lower != 'disabled'
          block:
            - name: Set hostname fact
              ansible.builtin.set_fact:
                hostname: '{{ longhorn_vars.kubernetes.gateway.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'

            - name: Create frontend gateway
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'gateway.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create http route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'http_route.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create https route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'https_route.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

        - name: Set frontend loadbalancer ip
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'loadbalancer.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
          when: cloudflare_vars.kubernetes.host.domain | lower == 'disabled'
