---
- name: Role Facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Role Reset
  block:
    - name: Remove repository
      kubernetes.core.helm_repository:
        name: '{{ longhorn_vars.kubernetes.helm.repository.org }}'
        repo_state: absent
      when:
        - ansible_host in k3s_map.server.hosts
        - "'helm' in ansible_facts.packages"

    - name: Remove directory
      ansible.builtin.file:
        path: '{{ longhorn_map.directory.data }}'
        state: absent
