---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - external-dns
    - k3s
    - victoria-metrics
    - longhorn
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ longhorn_project.url }}/{{ longhorn_project.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Set credentials fact
          ansible.builtin.set_fact:
            credentials: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
          no_log: true

        - name: Set string data fact
          ansible.builtin.set_fact:
            string_data:
              user: "{{ credentials.stringData['CIFS_USERNAME'] | b64encode }}"
              password: "{{ credentials.stringData['CIFS_PASSWORD'] | b64encode }}"
          no_log: true

        - name: Validate credentials values
          ansible.builtin.debug:
            msg: "{{ credentials | combine({'stringData': {'CIFS_PASSWORD': string_data.password, 'CIFS_USERNAME': string_data.user}}) }}"

        - name: Validate gateway values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'gateway.j2') }}"

        - name: Validate insecure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') }}"

        - name: Validate secure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') }}"

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            longhorn_postinstall: false

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            longhorn_postinstall: true

        - name: Validate postinstall chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Add repository
          kubernetes.core.helm_repository:
            name: '{{ longhorn_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ longhorn_vars.kubernetes.helm.repository.url }}'

        - name: Simulate chart deployment
          ansible.builtin.command:
            cmd: >-
              helm diff upgrade {{ longhorn_vars.kubernetes.helm.chart.name }} {{ longhorn_map.helm.chart.reference }}
                --kubeconfig {{ k3s_project.cluster.kubeconfig }}
                --namespace {{ longhorn_vars.kubernetes.namespace }}
                --version {{ longhorn_vars.kubernetes.helm.chart.version }}
                --context 3 --values -
            stdin: "{{ lookup('ansible.builtin.template', 'values.j2') }}"
          register: result
          delay: 1
          retries: 3
          until: result is not failed
          changed_when: false

        - name: Chart deployment simulation result
          ansible.builtin.debug:
            msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"
