---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert-manager
    - external-dns
    - k3s
    - victoria-metrics
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ victoriametrics_project.url }}/{{ victoriametrics_project.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Set credentials fact
          ansible.builtin.set_fact:
            credentials: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
          no_log: true

        - name: Set string data fact
          ansible.builtin.set_fact:
            string_data:
              user: "{{ credentials.stringData['admin-user'] | b64encode }}"
              password: "{{ credentials.stringData['admin-password'] | b64encode }}"
          no_log: true

        - name: Validate alertmanager configuration values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_alertmanager.j2') }}"

        - name: Validate credentials values
          ansible.builtin.debug:
            msg: "{{ credentials | combine({'stringData': {'admin-password': string_data.password, 'admin-user': string_data.user}}) }}"

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"
