---
cilium_vars:
  kubernetes:
    agent:
      resources:
        limits:
          cpu: null
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
    bpf:
      datapath_mode: netkit
      masquerade: true
    cgroup:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    client:
      rate_limit:
        burst: 100
        qps: 50
    cni:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    envoy:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    helm:
      chart:
        name: cilium
        version: v1.16.4
      repository:
        name: cilium
        org: cilium
        url: https://helm.cilium.io
    hubble:
      relay:
        replicas: 2
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
        retry_timeout: 10s
      ui:
        backend:
          resources:
            limits:
              cpu: null
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
        frontend:
          resources:
            limits:
              cpu: null
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
        gateway:
          service: hubble-ui
          subdomain: hubble
        infrastructure:
          annotations:
            io.cilium/lb-ipam-ips: 192.168.4.19
        replicas: 1
      tls:
        auto:
          method: certmanager
        certificate:
          common:
            name: hubble-common-certs
          root:
            name: hubble-root-certs
        cluster_issuer:
          name: hubble-cluster-issuer
    ip_masq_agent:
      enabled: true
      non_masquerade_cidrs:
        - 10.0.0.0/8
        - 192.168.1.0/24
    ipam:
      operator:
        cluster_pool: 10.42.0.0/16
    loadbalancer:
      algorithm: maglev
      ip_pool:
        blocks:
          start: 192.168.4.16
          stop: 192.168.4.50
        name: default-pool
      l2_announcement_policy:
        name: default-l2-announcement-policy
      table_size: 16381
    namespace: kube-system
    operator:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  release:
    cli:
      file: cilium-linux-arm64.tar.gz
      repository:
        name: cilium-cli
        org: cilium
      version: v0.16.20
    gateway_api:
      file: experimental-install.yaml
      repository:
        name: gateway-api
        org: kubernetes-sigs
      version: v1.2.0
    hubble:
      file: hubble-linux-arm64.tar.gz
      repository:
        name: hubble
        org: cilium
      version: v1.16.4
