---
cilium_vars:
  kubernetes:
    agent:
      resources:
        limits:
          cpu: null
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
    bpf:
      clock_probe: true
      datapath_mode: netkit
      external_access: false
      masquerade: true
      tproxy: true
      vlan_bypass_ids:
        - 1
        - 4
    cgroup:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    client:
      rate_limit:
        burst: 100
        qps: 50
    cni:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    envoy:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    helm:
      chart:
        name: cilium
        version: v1.16.4
      repository:
        name: cilium
        org: cilium
        url: https://helm.cilium.io
    hubble:
      relay:
        replicas: 2
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
        retry_timeout: 10s
      ui:
        enabled: true
        backend:
          resources:
            limits:
              cpu: null
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
        frontend:
          resources:
            limits:
              cpu: null
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
        gateway:
          service: hubble-ui
          subdomain: hubble
        infrastructure:
          # -- (string) `CiliumLoadBalancerIPPool` address, set at global level
          # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) infrastructure
          loadbalancer:
        replicas: 1
      tls:
        auto:
          method: certmanager
        certificate:
          common:
            name: hubble-common-certs
          root:
            name: hubble-root-certs
        cluster_issuer:
          name: hubble-cluster-issuer
    ingress_controller:
      # -- (string) Assign the first `CiliumLoadBalancerIPPool` address, set at global level
      # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) infrastructure
      service:
    ip_masq_agent:
      enabled: false
      non_masquerade_cidrs:
        - 10.0.0.0/8
        - 192.168.0.0/16
    ipam:
      operator:
        cluster_pool: 10.42.0.0/16
    loadbalancer:
      algorithm: maglev
      ip_pool:
        blocks:
          # -- (string) First `CiliumLoadBalancerIPPool` address, set at global level
          # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) infrastructure
          start:
          # -- (string) Last `CiliumLoadBalancerIPPool` address, set at global level
          # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) infrastructure
          stop:
        name: default-pool
      l2_announcement_policy:
        name: default-l2-announcement-policy
      table_size: 16381
    log_options:
      # -- Available options are `Info`, `Warn` and `Error`
      level: Warn
    namespace: kube-system
    operator:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  release:
    cli:
      file: cilium-linux-arm64.tar.gz
      repository:
        name: cilium-cli
        org: cilium
      version: v0.16.20
    gateway_api:
      file: standard-install.yaml
      repository:
        name: gateway-api
        org: kubernetes-sigs
      version: v1.2.1
    hubble:
      file: hubble-linux-arm64.tar.gz
      repository:
        name: hubble
        org: cilium
      version: v1.16.4
