---
certmanager_vars:
  kubernetes:
    cainjector:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    controller:
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    helm:
      chart:
        name: cert-manager
        org: cert-manager
        version: v1.16.2
      repository:
        name: cert-manager
        org: jetstack
        url: https://charts.jetstack.io
    namespace: kube-system
    tls:
      cluster_issuer:
        name: certmanager-cluster-issuer
    webhook:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  release:
    checksums: checksums.txt
    file: cmctl_linux_arm64
    repository:
      name: cmctl
      org: cert-manager
    version: v2.1.1
