---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cloudflare
    - argocd
  loop_control:
    loop_var: role

- name: Role Validation
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ argocd_project.url }}/{{ argocd_project.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release checksum url
      ansible.builtin.uri:
        url: '{{ argocd_project.release.checksum }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release file url
      ansible.builtin.uri:
        url: '{{ argocd_project.release.file }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed
