---
- name: Role Facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Validation
  run_once: true
  block:
    - name: Validate project tag url
      ansible.builtin.uri:
        url: '{{ argocd_project_url_tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release binary url
      ansible.builtin.uri:
        url: '{{ argocd_release_url_file }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release checksums url
      ansible.builtin.uri:
        url: '{{ argocd_release_url_checksums }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed
