---
victoriametrics_vars:
  kubernetes:
    alertmanager:
      config:
        route:
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        subdomain: alertmanager
      log_level: WARN
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    default_dashboards:
      timezone: utc
    helm:
      chart:
        alias: vmks
        name: victoria-metrics-k8s-stack
        version: v0.28.4
      repository:
        grafana:
          name: helm-charts
          org: grafana
          url: https://grafana.github.io
        prometheus:
          name: helm-charts
          org: prometheus-community
          url: https://prometheus-community.github.io
        victoriametrics:
          name: helm-charts
          org: VictoriaMetrics
          url: https://victoriametrics.github.io
    grafana:
      ingress:
        enabled: true
        subdomain: grafana
      log_level: WARN
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      sidecar:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      user:
        name: admin
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64373766356138653633346638343234336132383737616530303636366262313534656163616435
          3363396663333933306431363038316239373164386332660a616136666438313933353762373063
          38323135393830336132393239363236373961336464623432363338616266626334393233366263
          6164623332633535310a626532356161363563303036353838306234306562303333333231643432
          38383463653931373134663230383033666264646364316563663636303736326630
    kube_state_metrics:
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    namespace: kube-system
    victoria_metrics_operator:
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    prometheus_node_exporter:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    vmagent:
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        subdomain: agent
      log_level: WARN
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
    vmalert:
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        subdomain: alert
      log_level: WARN
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    vmcluster:
      enabled: true
      replication_factor: 2
      retention_period: 72h
      vminsert:
        ingress:
          enabled: false
          subdomain: insert
        log_level: WARN
        replicas: 1
        resources:
          limits:
            cpu: null
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
      vmselect:
        ingress:
          enabled: true
          subdomain: metrics
        log_level: WARN
        replicas: 1
        resources:
          limits:
            cpu: null
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
        storage: 2Gi
      vmstorage:
        ingress:
          enabled: false
          subdomain: storage
        log_level: WARN
        replicas: 1
        resources:
          limits:
            cpu: null
            memory: 2560Mi
          requests:
            cpu: 10m
            memory: 2560Mi
        storage: 20Gi
