---
victoriametrics_vars:
  kubernetes:
    alertmanager:
      config:
        route:
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        subdomain: alertmanager
      log_level: WARN
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      storage:
        enabled: false
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 5Gi
    default_dashboards:
      timezone: utc
    helm:
      chart:
        alias: vmks
        name: victoria-metrics-k8s-stack
        version: v0.28.4
      repository:
        grafana:
          name: helm-charts
          org: grafana
          url: https://grafana.github.io
        prometheus:
          name: helm-charts
          org: prometheus-community
          url: https://prometheus-community.github.io
        victoriametrics:
          name: helm-charts
          org: VictoriaMetrics
          url: https://victoriametrics.github.io
    grafana:
      ingress:
        enabled: true
        subdomain: grafana
      log_level: WARN
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      sidecar:
        # -- Sidecar resources
        resources:
          # -- CPU and memory limits
          limits:
            cpu: null
            memory: 128Mi
          # -- CPU and memory requests
          requests:
            cpu: 10m
            memory: 128Mi
      # -- Login credentials for Grafana UI
      user:
        # -- User name used to access Grafana UI
        # @default -- Set value into <a href="../../inventory/cluster/group_vars/all.yaml">all.yaml</a> variables
        name:
        # -- User password used to access Grafana UI
        # @default -- Set value into <a href="../../inventory/cluster/group_vars/all.yaml">all.yaml</a> variables
        password:
    kube_state_metrics:
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    namespace: kube-system
    victoria_metrics_operator:
      log_level: error
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    prometheus_node_exporter:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    vmagent:
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        subdomain: agent
      log_level: WARN
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      storage:
        enabled: false
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 5Gi
    vmalert:
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        subdomain: alert
      log_level: WARN
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    vmcluster:
      enabled: true
      replication_factor: 2
      retention_period: 72h
      vminsert:
        hpa:
          enabled: true
          min_replicas: 2
          max_replicas: 4
          resource:
            name: memory
            target:
              utilization: 80
        ingress:
          enabled: false
          subdomain: insert
        log_level: WARN
        resources:
          limits:
            cpu: null
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
      vmselect:
        hpa:
          enabled: true
          min_replicas: 2
          max_replicas: 4
          resource:
            name: memory
            target:
              utilization: 80
        ingress:
          enabled: true
          subdomain: metrics
        log_level: WARN
        resources:
          limits:
            cpu: null
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 256Mi
        storage:
          enabled: false
          access_modes:
            - ReadWriteOnce
          class: longhorn
          size: 5Gi
      vmstorage:
        ingress:
          enabled: false
          subdomain: storage
        log_level: WARN
        replicas: 2
        resources:
          limits:
            cpu: null
            memory: 2560Mi
          requests:
            cpu: 10m
            memory: 2560Mi
        storage:
          enabled: false
          access_modes:
            - ReadWriteOnce
          class: longhorn
          size: 20Gi
