---
- name: Node Configuration
  notify: Restart service
  block:
    - name: Create registries file
      ansible.builtin.template:
        src: registries.j2
        dest: '{{ k3s_map.cluster.registries }}'
        owner: root
        group: root
        mode: '0600'
      when:
        - ansible_host not in k3s_map.server.hosts
        - k3s_vars.cluster.controlplane.tainted

- name: Server Configuration
  when: ansible_host in k3s_map.server.hosts
  block:
    - name: Add variable to environment file
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: KUBECONFIG={{ k3s_map.cluster.kubeconfig }}
        regexp: ^KUBECONFIG

    - name: Create symlinks
      ansible.builtin.file:
        path: '{{ k3s_vars.directory.bin }}/{{ item }}'
        src: '{{ k3s_map.node.binary }}'
        state: link
      loop:
        - crictl
        - ctr
        - kubectl

    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        state: drained
        timeout: 30
      any_errors_fatal: true

    - name: Token Setup
      when: k3s_project.token | length == 0
      no_log: true
      run_once: true
      block:
        - name: Wait for token creation
          ansible.builtin.wait_for:
            path: '{{ k3s_vars.directory.lib }}/server/node-token'

        - name: Read token
          ansible.builtin.slurp:
            path: '{{ k3s_vars.directory.lib }}/server/node-token'
          register: node_token

        - name: Set token fact
          ansible.builtin.set_fact:
            token: '{{ node_token.content | b64decode | trim }}'

    - name: Kubepug Setup
      block:
        - name: Checksum Setup
          run_once: true
          block:
            - name: Get remote checksum
              ansible.builtin.uri:
                url: '{{ k3s_project.release.kubepug.checksum }}'
                return_content: true
              register: checksum
              check_mode: false

            - name: Set sha256 checksum fact
              ansible.builtin.set_fact:
                sha256_checksum: "{{ item.split(' ')[0] }}"
              loop: "{{ checksum.content.split('\n') }}"
              when: item | regex_search(k3s_vars.release.kubepug.file + '$')

        - name: Download kubepug archive
          ansible.builtin.get_url:
            url: '{{ k3s_project.release.kubepug.file }}'
            checksum: sha256:{{ sha256_checksum }}
            dest: /tmp
            owner: root
            group: root
            mode: '0644'
          register: result
          delay: 1
          retries: 3
          until: result is not failed
          check_mode: false

        - name: Install kubepug binary
          ansible.builtin.unarchive:
            src: /tmp/{{ k3s_vars.release.kubepug.file }}
            dest: '{{ k3s_vars.directory.bin }}'
            owner: root
            group: root
            mode: '0755'
            remote_src: true

        - name: Remove kubepug archive
          ansible.builtin.file:
            path: /tmp/{{ k3s_vars.release.kubepug.file }}
            state: absent
          check_mode: false

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  when: k3s_flush_handlers

- name: Local Configuration
  when:
    - k3s_vars.cluster.kubeconfig.local
    - ansible_host in ['localhost', k3s_map.server.default_host]
  run_once: true
  block:
    - name: Create temporary file
      ansible.builtin.tempfile:
        prefix: kubeconfig.
      register: kubeconfig

    - name: Copy kubeconfig file
      ansible.builtin.copy:
        src: '{{ k3s_map.cluster.kubeconfig }}'
        dest: '{{ kubeconfig.path }}'
        mode: preserve
        remote_src: true

    - name: Get file content
      ansible.builtin.slurp:
        path: '{{ kubeconfig.path }}'
      register: file

    - name: Set datasource fact
      ansible.builtin.set_fact:
        datasource: '{{ file.content | b64decode | from_yaml }}'

    - name: Set datasource parameters
      ansible.builtin.set_fact:
        datasource: '{{ datasource | combine(parameters) }}'
      vars:
        parameters:
          clusters:
            - cluster:
                certificate-authority-data: "{{ datasource.clusters[0].cluster['certificate-authority-data'] }}"
                server: https://{{ k3s_vars.server.api.host if k3s_map.cluster.ha else k3s_map_server.default_ip }}:{{ k3s_vars.server.api.port }}
              name: '{{ datasource.clusters[0].name }}'

    - name: Update kubeconfig file
      ansible.builtin.copy:
        content: '{{ datasource | to_nice_yaml(indent=2) }}'
        dest: '{{ kubeconfig.path }}'
        mode: preserve
        remote_src: true

    - name: Copy kubeconfig file locally
      ansible.builtin.fetch:
        src: '{{ kubeconfig.path }}'
        dest: "{{ k3s_vars.directory.kubeconfig + '/config' }}"
        flat: true

    - name: Remove kubeconfig file
      ansible.builtin.file:
        path: '{{ kubeconfig.path }}'
        state: absent

    - name: Set local kubeconfig file permissions
      ansible.builtin.file:
        path: "{{ k3s_vars.directory.kubeconfig + '/config' }}"
        mode: '0600'
        state: file
      delegate_to: localhost
      become: false
