---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Validation
  run_once: true
  block:
    - name: Validate inventory
      ansible.builtin.assert:
        that: k3s_map.cluster.ha or k3s_map.cluster.non_ha
        fail_msg: |-
          ERROR: Invalid number of 'server' type nodes.
            - Defined nodes: {{ k3s_map.server.hosts | length }} ({{ k3s_map.server.hosts | join(', ') }})
            - Valid values: 1, higher than 2
          FIXES:
            - Update the number of 'server' type nodes, into inventory file.
        quiet: true

    - name: Validate release checksum url
      ansible.builtin.uri:
        url: '{{ item }}'
        timeout: 5
      loop:
        - '{{ k3s_project.release.k3s.checksum }}'
        - '{{ k3s_project.release.kubepug.checksum }}'
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release file url
      ansible.builtin.uri:
        url: '{{ item }}'
        timeout: 5
      loop:
        - '{{ k3s_project.release.k3s.file }}'
        - '{{ k3s_project.release.kubepug.file }}'
      register: result
      delay: 1
      retries: 3
      until: result is not failed
