---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - external-dns
    - k3s
    - victoria-metrics
    - coredns
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ coredns_project.url }}/{{ coredns_project.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            coredns_postinstall: false

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Set chart values fact
          ansible.builtin.set_fact:
            chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml }}"

        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            coredns_postinstall: true

        - name: Validate postinstall chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Update chart values fact
          ansible.builtin.set_fact:
            chart_values: "{{ chart_values | combine(lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml, recursive=true) }}"

        - name: Add repository
          kubernetes.core.helm_repository:
            name: '{{ coredns_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ coredns_map.helm.repository.url }}'

        - name: Simulate chart deployment
          ansible.builtin.command:
            cmd: >-
              helm diff upgrade {{ coredns_vars.kubernetes.helm.chart.name }} {{ coredns_map.helm.chart.reference }}
                --kubeconfig {{ k3s_project.cluster.kubeconfig }}
                --namespace {{ coredns_vars.kubernetes.namespace }}
                --version {{ coredns_vars.kubernetes.helm.chart.version }}
                --context 3 --values -
            stdin: '{{ chart_values | to_yaml }}'
          register: result
          delay: 1
          retries: 3
          until: result is not failed
          changed_when: false

        - name: Chart deployment simulation result
          ansible.builtin.debug:
            msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"
