---
cluster_vars:
  device:
    # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/server/#storage-devices), for details
    enabled: true
    id: '2:2'
    name: 'ASMedia Technology'
  hardware:
    # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/server/#hardware), for details
    architecture: aarch64
    # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/server/#hardware), for details
    product: 'Raspberry Pi'
  service:
    bluetooth:
      # -- By default, related `apt` packages are not installed
      enabled: false
    cloud_init:
      enabled: false
    postfix:
      enabled: true
      protocols: ipv4
      relay:
        # -- iCloud mail server relay host
        host: smtp.mail.me.com
        port: 587
      # -- (string) Postfix user credentials, set at global level
      # @default -- Set values into [all.yaml](../../inventory/cluster/group_vars/all.yaml) `credentials` collection
      user:
    snapd:
      enabled: false
    unattended_upgrades:
      # -- See [documentation](https://help.ubuntu.com/community/AutomaticSecurityUpdates), for details
      enabled: true
      mail_report: only-on-error
      remove_deps: 'true'
    wifi:
      # -- By default, related `apt` packages are not installed
      enabled: false
  ssh:
    # -- Public `.ssh` key, generated with `ed25519` algorithm
    key: id_ed25519.pub
    # -- Full path to `.ssh` directory, a hardcoded value can be used
    path: "{{ lookup('ansible.builtin.env', 'HOME') + '/.ssh' }}"
