---
- name: Set project fact
  ansible.builtin.set_fact:
    victoriametrics_project:
      chart:
        name: '{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        version: '{{ victoriametrics_vars.kubernetes.helm.chart.version[1:] }}'
      ingress:
        alertmanager:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
            io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.alertmanager.ingress.ip }}'
          hostname: '{{ victoriametrics_vars.kubernetes.alertmanager.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: 'alertmanager-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        grafana:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
            io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.grafana.ingress.ip }}'
          hostname: '{{ victoriametrics_vars.kubernetes.grafana.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana'
        vmagent:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
            io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.vmagent.ingress.ip }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmagent.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: 'vmagent-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        vmalert:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
            io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.vmalert.ingress.ip }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmalert.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: 'vmalert-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        vmcluster:
          vminsert:
            annotations:
              cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
              io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.vmcluster.vminsert.ingress.ip }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vminsert.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
            name: 'vminsert-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
          vmselect:
            annotations:
              cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
              io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.vmcluster.vmselect.ingress.ip }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vmselect.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
            name: 'vmselect-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
          vmstorage:
            annotations:
              cert-manager.io/cluster-issuer: '{{ cloudflare_cluster_issuer }}'
              io.cilium/lb-ipam-ips: '{{ victoriametrics_vars.kubernetes.vmcluster.vmstorage.ingress.ip }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vmstorage.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
            name: 'vmstorage-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
      repository:
        - name: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.name }}'
          org: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.org }}'
          url: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.url }}'
        - name: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.name }}'
          org: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.org }}'
          url: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.url }}'
        - name: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name }}'
          org: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org }}'
          url: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.url }}'
      secret:
        grafana:
          name: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana-user-account'
  run_once: true

- name: Set project chart fact
  ansible.builtin.set_fact:
    victoriametrics_project_chart: '{{ victoriametrics_project.repository[2].org }}/{{ victoriametrics_project.chart.name }}'
  run_once: true

- name: Set project release fact
  ansible.builtin.set_fact:
    victoriametrics_project_release: '{{ victoriametrics_project.repository[2].org }}/{{ victoriametrics_project.repository[2].name }}'
  run_once: true

- name: Set project tag fact
  ansible.builtin.set_fact:
    victoriametrics_project_tag: '{{ victoriametrics_project.chart.name }}-{{ victoriametrics_project.chart.version }}'
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    victoriametrics_project_url: https://github.com/{{ victoriametrics_project_release }}/releases/tag
  run_once: true

- name: Set project url tag fact
  ansible.builtin.set_fact:
    victoriametrics_project_url_tag: '{{ victoriametrics_project_url }}/{{ victoriametrics_project_tag }}'
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    victoriametrics_vars: '{{ victoriametrics_vars }}'
  run_once: true
