---
- name: Set project fact
  ansible.builtin.set_fact:
    victoriametrics_project:
      chart:
        name: '{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        version: '{{ victoriametrics_vars.kubernetes.helm.chart.version[1:] }}'
      gateway:
        service:
          alertmanager: 'vmalertmanager-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
          grafana: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana'
      hostname:
        alertmanager: '{{ victoriametrics_vars.kubernetes.alertmanager.gateway.subdomain }}.{{ cloudflare_vars.kubernetes.gateway.domain }}'
        grafana: '{{ victoriametrics_vars.kubernetes.grafana.gateway.subdomain }}.{{ cloudflare_vars.kubernetes.gateway.domain }}'
      repository:
        - name: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.name }}'
          org: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.org }}'
          url: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.url }}'
        - name: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.name }}'
          org: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.org }}'
          url: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.url }}'
        - name: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name }}'
          org: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org }}'
          url: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.url }}'
      secret:
        grafana: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana'
  run_once: true

- name: Set project chart fact
  ansible.builtin.set_fact:
    victoriametrics_project_chart: '{{ victoriametrics_project.repository[2].org }}/{{ victoriametrics_project.chart.name }}'
  run_once: true

- name: Set project release fact
  ansible.builtin.set_fact:
    victoriametrics_project_release: '{{ victoriametrics_project.repository[2].org }}/{{ victoriametrics_project.repository[2].name }}'
  run_once: true

- name: Set project tag fact
  ansible.builtin.set_fact:
    victoriametrics_project_tag: '{{ victoriametrics_project.chart.name }}-{{ victoriametrics_project.chart.version }}'
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    victoriametrics_project_url: https://github.com/{{ victoriametrics_project_release }}/releases/tag
  run_once: true

- name: Set project url tag fact
  ansible.builtin.set_fact:
    victoriametrics_project_url_tag: '{{ victoriametrics_project_url }}/{{ victoriametrics_project_tag }}'
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    victoriametrics_vars: '{{ victoriametrics_vars }}'
  run_once: true
