---
- name: Set map fact
  ansible.builtin.set_fact:
    victoriametrics_map:
      credentials:
        grafana:
          secret: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana-credentials'
      helm:
        chart:
          version: '{{ victoriametrics_vars.kubernetes.helm.chart.version[1:] }}'
        repository:
          - name: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.name }}'
            org: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.org }}'
            url: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.url }}'
          - name: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.name }}'
            org: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.org }}'
            url: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.url }}'
          - name: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name }}'
            org: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org }}'
            url: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.url }}'
        timeout: 5m0s
      infrastructure:
        alertmanager:
          annotations:
            io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.alertmanager }}'
        grafana:
          annotations:
            io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.grafana }}'
        vmagent:
          annotations:
            io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.vmagent }}'
        vmalert:
          annotations:
            io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.vmalert }}'
        vmcluster:
          vminsert:
            annotations:
              io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.vmcluster.vminsert }}'
          vmselect:
            annotations:
              io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.vmcluster.vmselect }}'
          vmstorage:
            annotations:
              io.cilium/lb-ipam-ips: '{{ global_map.infrastructure[role_name].loadbalancer.vmcluster.vmstorage }}'
      ingress:
        alertmanager:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.alertmanager.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: 'alertmanager-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        grafana:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.grafana.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana'
        vmagent:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmagent.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: 'vmagent-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        vmalert:
          annotations:
            cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmalert.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
          name: 'vmalert-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
        vmcluster:
          vminsert:
            annotations:
              cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vminsert.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
            name: 'vminsert-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
          vmselect:
            annotations:
              cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vmselect.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
            name: 'vmselect-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
          vmstorage:
            annotations:
              cert-manager.io/cluster-issuer: '{{ cloudflare_resources.cluster.issuer }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vmstorage.ingress.subdomain }}.{{ cloudflare_vars.kubernetes.host.domain }}'
            name: 'vmstorage-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    victoriametrics_project:
      helm:
        chart:
          reference: '{{ victoriametrics_map.helm.repository[2].org }}/{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
      tag: '{{ victoriametrics_vars.kubernetes.helm.chart.name }}-{{ victoriametrics_map.helm.chart.version }}'
      url: 'https://github.com/{{ victoriametrics_map.helm.repository[2].org }}/{{ victoriametrics_map.helm.repository[2].name }}/releases/tag'
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    victoriametrics_vars: '{{ victoriametrics_vars }}'
  run_once: true
