---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - cloudflare
    - k3s

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        state: drained
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ item.org }}'
        repo_url: '{{ item.url }}/{{ item.name }}'
      loop: '{{ victoriametrics_project.repository }}'

    - name: Chart Setup
      run_once: true
      block:
        - name: Create grafana secret
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'grafana_secret.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
            wait: true

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            victoriametrics_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ victoriametrics_project_chart }}'
            chart_version: '{{ victoriametrics_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
            name: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}'
            namespace: '{{ victoriametrics_vars.kubernetes.namespace }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Gateway Setup
          when: cloudflare_vars.kubernetes.gateway.domain | lower != 'disabled'
          block:
            - name: Create alertmanager gateway
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'alertmanager_gateway.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create alertmanager http route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'alertmanager_http_route.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create alertmanager https route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'alertmanager_https_route.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create grafana gateway
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'grafana_gateway.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create grafana http route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'grafana_http_route.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create grafana https route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'grafana_https_route.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true
