---
argocd_vars:
  kubernetes:
    application_set:
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    configs:
      cm:
        admin:
          enabled: false
        exec:
          enabled: true
        status_badge:
          enabled: true
      params:
        server:
          insecure: true
    controller:
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    dex:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    haproxy:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    helm:
      chart:
        name: argo-cd
        version: v7.7.10
      repository:
        name: argo-helm
        org: argoproj
        url: https://argoproj.github.io
    global:
      logging:
        level: warn
    namespace: kube-system
    notifications:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    redis:
      ha:
        # -- Redis HA requires at least 3 worker nodes
        enabled: false
        storage:
          enabled: false
          access_modes:
            - ReadWriteOnce
          class: longhorn
          size: 10Gi
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    repo_server:
      autoscaling:
        # -- If `false`, `replicas` value is set from `min_replicas` value
        enabled: true
        min_replicas: 1
        max_replicas: 3
        target:
          utilization_percentage:
            cpu: null
            memory: 80
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    server:
      application:
        namespaces:
          - kube-system
      autoscaling:
        # -- If `false`, `replicas` value is set from `min_replicas` value
        enabled: true
        min_replicas: 1
        max_replicas: 3
        target:
          utilization_percentage:
            cpu: null
            memory: 80
      credentials:
        admin:
          # -- (string) ArgoCD UI admin password, set at global level
          # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) `credentials` collection
          password:
        user:
          # -- (string) ArgoCD UI user name, set at global level
          # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) `credentials` collection
          name:
          # -- (string) ArgoCD UI user password, set at global level
          # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) `credentials` collection
          password:
      gateway:
        service: argo-cd-argocd-server
        subdomain: argocd
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  release:
    checksum: cli_checksums.txt
    file: argocd-linux-arm64
    repository:
      name: argo-cd
      org: argoproj
    version: v2.13.2
