---
- name: Set map fact
  ansible.builtin.set_fact:
    cloudflare_map:
      acme:
        server: "{{ '-staging' if cloudflare_vars.kubernetes.acme.server | lower == 'staging' | default('') }}"
      helm:
        chart:
          reference: '{{ cloudflare_vars.kubernetes.helm.repository.org }}/{{ cloudflare_vars.kubernetes.helm.chart.name }}'
          version: '{{ cloudflare_vars.kubernetes.helm.chart.version[1:] }}'
        repository:
          name: '{{ cloudflare_vars.kubernetes.helm.repository.org }}/{{ cloudflare_vars.kubernetes.helm.repository.name }}'
          url: '{{ cloudflare_vars.kubernetes.helm.repository.url }}/{{ cloudflare_vars.kubernetes.helm.repository.name }}'
      tls:
        key:
          prefix: '{{ cloudflare_vars.kubernetes.tls.key_prefix }}'
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    cloudflare_project:
      tag: '{{ cloudflare_vars.kubernetes.helm.chart.name }}-helm-chart-{{ cloudflare_map.helm.chart.version }}'
      url: https://github.com/{{ cloudflare_map.helm.repository.name }}/releases/tag
  run_once: true

- name: Set resources fact
  ansible.builtin.set_fact:
    cloudflare_resources:
      acme:
        server:
          url: https://acme{{ cloudflare_map.acme.server }}-v02.api.letsencrypt.org/directory
      cluster:
        issuer: '{{ cloudflare_vars.kubernetes.tls.cluster_issuer.name }}{{ cloudflare_map.acme.server }}'
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    cloudflare_vars: '{{ cloudflare_vars }}'
  run_once: true
